# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fae611efa7463250e271d4d1429dc98c648d732bdbad3a1a223a38a797c83e05f96c6c4a9801819c91eeaf55b4cef50e181c8a85c47007fd591f306e1d6d8bce

test:
  secret_key_base: 62f4749a69159db4925a5a6ef7f3760045a7ee120cccdcf677065827348a0982d4c5dfc8e8be7a7b68e56339746a33210c15ef49337737e9e82d033aeba02b14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
